### ISSUE TITLE
Feature Requests - checklist.

### ISSUE THREAD

**Issue by ghost** [MGeymer/LDYOM#46]
### **Features from the main storyline:**
- [ ] Ability to skip trips, cutscenes & phone calls.
- [ ] Ability to enter "turret-mode".
- [ ] _Re-implementation_ of vehicle "sunk" objective. (from beta v0.7.2)
- [ ] Ability to copy mini-game-segments from Cesar Vialpando, Life's a Beach & Nightclub Dance.
- [ ] Ability to heal from Dispensers.
- [ ] Fixed vehicle and pickup spawns from vanilla, except collectibles.

### **Features for Designers:**
- [ ] Hotkeys for Jetpack.
- [ ] Hotkeys to teleport to selected, first/last or a specific objective.
- [ ] Make cutscene cameras visible in editing scene.
- [ ] Ability to edit objectives from the scene itself i.e. without opening the menu.
- [ ] Implementation of Interior Selection (preferably using sliders).
- [ ] Automatic creation of "Start mission" and "End mission" objectives upon starting ldyom.
- [ ] Checkpoint entity should automatically tie "Spawn Before" and "Delete After" parameter to the selected objective.
- [ ] Objectives checkpoint box should automatically pick the most recently created checkpoint entity.
- [ ] Infinite sprint when in editing-phase.
- [ ] Automatically setting radio off when in editing-phase & reverting the change during mission testing.
- [ ] Ability to 'go back' in menu.

### **Elusive Features:**
- [ ] LDYOM-Exclusive cheat codes for debugging, like airbreak, toggle enex markers. For eg: "LDSTOP" is used to force stop mission-testing.
- [ ] Implementation of Carrec Path from MM.
- [ ] Ability to play cutscenes from the main storyline.
- [ ] Auto-update implementation.
- [ ] Implementation of "interpolation" graph editor for cutscenes & character animations, instead of presets.
- [ ] Ability to attach objects to specific parts of actors or player.

_I won't be adding any more feature requests until I fully test the next stable release._

@GeTechG No need to focus on these until LDYOM becomes stable enough for basic mission creation.

**Comment by GeTechG** [comment]
> * Ability to change objective names.

If I understand you correctly, do you want to rename it in the list? If yes, then such a function is in all lists on the RCM.

**Comment by ghost** [comment]
I am sorry. I forgot.

**Comment by ghost** [comment]
@GeTechG Are you able to check the list items? Will these features even be implemented in ldyom?

**Comment by GeTechG** [comment]
> @GeTechG Are you able to check the list items? Will these features even be implemented in ldyom?

I looked it up, with some things I think differently, but in one way or another everything will be.
